version: "3.8"
services:
  backend:
    build: ./backend
    container_name: lxn-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: .
    container_name: lxn-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
