name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app || git clone https://github.com/<your-username>/<your-repo>.git /home/ubuntu/app
            cd /home/ubuntu/app
            git pull origin main
            npm install --production
            npm run build
            pm2 restart all || pm2 start npm --name "app" -- start
