name: Deploy to AWS EC2

on:
  push:
    branches:
      - main   # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup SSH using EC2 private key from GitHub Secrets
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          # Clone repo if not already present, else pull latest changes
          if [ ! -d ~/lxn-app ]; then
            git clone https://github.com/Vijetha-HD/lxn.git ~/lxn-app
          else
            cd ~/lxn-app && git pull origin main
          fi

          cd ~/lxn-app

          # Install project dependencies
          npm install --legacy-peer-deps

          # Build frontend if project has a frontend folder
          if [ -d frontend ]; then
            cd frontend && npm install --legacy-peer-deps && npm run build && cd ..
          fi

          # Start or restart backend with PM2
          if [ -d backend ]; then
          cd backend && pm2 start server.js --name lxn-app || pm2 restart lxn-app && cd ..
          elif [ -f server.js ]; then
          pm2 start server.js --name lxn-app || pm2 restart lxn-app
          fi

