name: Deploy to AWS EC2

on:
  push:
    branches:
      - main   # runs only when you push to main
  workflow_dispatch:  # 👈 lets you trigger manually too

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup SSH with EC2 key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      # Step 3: Deploy app to EC2
      - name: Deploy app to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash -s' << 'EOF'
            # Clone repo if not already present, else pull latest changes
            if [ ! -d ~/lxn-app ]; then
              git clone https://github.com/Vijetha-HD/lxn.git ~/lxn-app
            else
              cd ~/lxn-app && git pull origin main
            fi

            cd ~/lxn-app

            # Install dependencies
            npm install --legacy-peer-deps

            # Build frontend if exists
            if [ -d frontend ]; then
              cd frontend && npm install --legacy-peer-deps && npm run build && cd ..
            fi

            # Start or restart backend with PM2 (server.js is your entry point)
            if [ -d backend ]; then
              cd backend && pm2 start server.js --name lxn-app || pm2 restart lxn-app && cd ..
            elif [ -f server.js ]; then
              pm2 start server.js --name lxn-app || pm2 restart lxn-app
            fi

            pm2 save
          EOF
